/*
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class GoatComponentsProjectInfo extends DefaultProjectInfo {

}
