/*
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.parser.antlr;

import com.google.inject.Inject;
import com.sysma.goat.eclipse_plugin.parser.antlr.internal.InternalGoatComponentsParser;
import com.sysma.goat.eclipse_plugin.services.GoatComponentsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GoatComponentsParser extends AbstractAntlrParser {

	@Inject
	private GoatComponentsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGoatComponentsParser createParser(XtextTokenStream stream) {
		return new InternalGoatComponentsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public GoatComponentsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GoatComponentsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
