/*
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.ui.tests;

import com.google.inject.Injector;
import com.sysma.goat.eclipse_plugin.ui.internal.Eclipse_pluginActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GoatComponentsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Eclipse_pluginActivator.getInstance().getInjector("com.sysma.goat.eclipse_plugin.GoatComponents");
	}

}
