/*
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.validation

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GoatInfrastructureValidator extends AbstractGoatInfrastructureValidator {
}
