/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.scoping;

import com.sysma.goat.eclipse_plugin.scoping.AbstractGoatInfrastructureScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GoatInfrastructureScopeProvider extends AbstractGoatInfrastructureScopeProvider {
}
