/*
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GoatComponentsRuntimeModule extends AbstractGoatComponentsRuntimeModule {
}
