/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.ui.wizard;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.resource.FileExtensionProvider;

@SuppressWarnings("all")
public class GoatComponentsNewProjectWizardInitialContents {
  @Inject
  private FileExtensionProvider fileExtensionProvider;
  
  public void generateInitialContents(final IFileSystemAccess2 fsa) {
    String _primaryFileExtension = this.fileExtensionProvider.getPrimaryFileExtension();
    String _plus = ("src/system." + _primaryFileExtension);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("infrastructure infr");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* This is an example system");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.newLine();
    _builder.append("process P {");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("component {} : P");
    _builder.newLine();
    fsa.generateFile(_plus, _builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("singleserver infr {");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("server : \"127.0.0.1:17654\"");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    fsa.generateFile("src/infrastructure.ginf", _builder_1);
  }
}
