/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.ui;

import com.sysma.goat.eclipse_plugin.ui.AbstractGoatComponentsUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GoatComponentsUiModule extends AbstractGoatComponentsUiModule {
  public GoatComponentsUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
