/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Wait For</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessWaitFor#getCond <em>Cond</em>}</li>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessWaitFor#getUpdate <em>Update</em>}</li>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessWaitFor#getPrint <em>Print</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getProcessWaitFor()
 * @model
 * @generated
 */
public interface ProcessWaitFor extends ProcessStatement
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cond</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Expression)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getProcessWaitFor_Cond()
   * @model containment="true"
   * @generated
   */
  Expression getCond();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessWaitFor#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Expression value);

  /**
   * Returns the value of the '<em><b>Update</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Update</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Update</em>' containment reference.
   * @see #setUpdate(Update)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getProcessWaitFor_Update()
   * @model containment="true"
   * @generated
   */
  Update getUpdate();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessWaitFor#getUpdate <em>Update</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Update</em>' containment reference.
   * @see #getUpdate()
   * @generated
   */
  void setUpdate(Update value);

  /**
   * Returns the value of the '<em><b>Print</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Print</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Print</em>' containment reference.
   * @see #setPrint(PrintStatement)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getProcessWaitFor_Print()
   * @model containment="true"
   * @generated
   */
  PrintStatement getPrint();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessWaitFor#getPrint <em>Print</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Print</em>' containment reference.
   * @see #getPrint()
   * @generated
   */
  void setPrint(PrintStatement value);

} // ProcessWaitFor
