/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Update Local Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.UpdateLocalAttribute#getAtname <em>Atname</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getUpdateLocalAttribute()
 * @model
 * @generated
 */
public interface UpdateLocalAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Atname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atname</em>' attribute.
   * @see #setAtname(String)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getUpdateLocalAttribute_Atname()
   * @model
   * @generated
   */
  String getAtname();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.UpdateLocalAttribute#getAtname <em>Atname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atname</em>' attribute.
   * @see #getAtname()
   * @generated
   */
  void setAtname(String value);

} // UpdateLocalAttribute
