/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.ide;

import com.sysma.goat.eclipse_plugin.ide.AbstractGoatComponentsIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GoatComponentsIdeModule extends AbstractGoatComponentsIdeModule {
}
